#! /usr/bin/env sh

konvert-all

export db_dir="db"

if [ -f .m4galleryrc ]; then
        . .m4galleryrc
fi

if [ -z "$1" ]; then
        if [ "$1" = "-d" ]; then
                if [ -z "$2" ]; then
                        export db_dir="$2"
                fi
        fi
fi

mkdir -p db

reindex_page(){
        file="$1"
        m4page -f "$file" -p -d "$db_dir"
        metavars "$file" > "$db_dir/$file.sh"
        export name=$(basename "$file")
        . "$file.sh";
        if [ ! -f contents.md ]; then touch contents.md; fi
        if [ ! "$(grep "$Title" contents.md)" ]; then
        if [ ! "$(grep "$Season" contents.md)" ]; then
        if [ ! "$(grep "$Episode" contents.md)" ]; then
        if [ ! "$(grep "$Description" contents.md)" ]; then
                echo " * **[$Title]($file.html)**" | tee -a contents.md
                echo "  * *Season* $Season, *Episode* $Episode" | tee -a contents.md
                echo "  * Genre: $Genre : $Description" | tee -a contents.md
                echo "  * *$Director .$Date*" | tee -a contents.md
        fi
        fi
        fi
        fi
        mv "$file.sh" "$db_dir/$name.sh"
}

regenerate_contents(){
        for file in $(find "$db_dir" -name *.sh); do
                . "$file";
                if [ ! -f contents.md ]; then touch contents.md; fi
                if [ ! "$(grep "$Title" contents.md)" ]; then
                if [ ! "$(grep "$Season" contents.md)" ]; then
                if [ ! "$(grep "$Episode" contents.md)" ]; then
                if [ ! "$(grep "$Description" contents.md)" ]; then
                        echo " * **[$Title]($file.html)**" | tee -a contents.md
                        echo "  * *Season* $Season, *Episode* $Episode" | tee -a contents.md
                        echo "  * Genre: $Genre : $Description" | tee -a contents.md
                        echo "  * *$Director .$Date*" | tee -a contents.md
                fi
                fi
                fi
                fi
        done
}

emit_index(){
        toc="$1"
        hdpage -p -t "$toc" > contents.html
        echo "  <body>" >> contents.html
        markdown contents.md >> contents.html
        echo "  </body>" >> contents.html
        echo "</html>" >> contents.html
        echo $name
}

for file in $(find -name *.mp4); do
        reindex_page "$file"
done

emit_index "Table_of_Contents"
