#! /usr/bin/env sh

konvert-all

export db_dir="db"

if [ -f .m4galleryrc ]; then
        . .m4galleryrc
fi

if [ -z "$1" ]; then
        if [ "$1" = "-d" ]; then
                if [ -z "$2" ]; then
                        export db_dir="$2"
                fi
        fi
fi

mkdir -p "$db_dir"

reindex_page(){
        file="$1"
        m4page -f "$file" -p -d "$db_dir" -n "../"
        export name=$(basename $file)
        echo "basename $name"
        metavars "$file" > "$db_dir/$name.sh"
        . "$db_dir/$name.sh";
        if [ ! -f contents.md ]; then touch contents.md; fi
        if [ ! "$(grep -C 1 "$Title" contents.md | \
                grep "$Season" | \
                grep "$Episode")" ]; then
                        echo " * **[$Title]($db_dir/$name.html)**" | tee -a contents.md
                        echo "  * *Season* $Season, *Episode* $Episode" | tee -a contents.md
                        echo "  * Genre: $Genre : $Description" | tee -a contents.md
                        echo "  * *$Director .$Date*" | tee -a contents.md
        fi
}

regenerate_contents(){
        for file in $(find "$db_dir" -name *.sh | sort); do
                . "$file";
                if [ ! -f contents.md ]; then touch contents.md; fi
                if [ ! "$(grep "$Title" contents.md | \
                        grep "$Season" | \
                        grep "$Episode")" ]; then
                                echo " * **[$Title]($db_dir/$name.html)**" | tee -a contents.md
                                echo "  * *Season* $Season, *Episode* $Episode" | tee -a contents.md
                                echo "  * Genre: $Genre : $Description" | tee -a contents.md
                                echo "  * *$Director .$Date*" | tee -a contents.md
                fi
        done
}

emit_index(){
        toc="$1"
        hdpage -p -t "$toc" > contents.html
        echo "  <body>" >> contents.html
        echo "  <div id=\"header\">" >> contents.html
        echo "# Notflix" | markdown >> contents.html
        echo "  </div>" >> contents.html
        echo "" >> contents.html
        markdown contents.md >> contents.html
        echo "  </body>" >> contents.html
        echo "</html>" >> contents.html
}

for file in $(find -name *.mp4 | sort); do
        reindex_page "$file"
done

emit_index "Table_of_Contents"
